### ISSUE TITLE
FF parsing is broken

### ISSUE THREAD

**Issue by dadambickford** [OscarGodson/EpicEditor#112]
![http://i.imgur.com/o3aH5.png](http://i.imgur.com/o3aH5.png)

Currently FF is doing this^ to table tags.

**Comment by OscarGodson** [comment]
It's also doing this for lists and stuff (see below). This is bad. God damn firefox. My gut instinct is that it has something to do with `_setText` or `_getText` https://github.com/OscarGodson/EpicEditor/blob/0.1.0-build-refactor/src/editor.js#L142-L151

I have a feeling because Firefox is the only browser that doesn't support innerText the innerHTML contains inline styles or something and it's passing it to marked (which doesn't know what to do with all that jumbled HTML) then off to the previewer with the inline styles.

![https://img.skitch.com/20120519-e9c1bkb79qfnii1srbqpitssnu.png](https://img.skitch.com/20120519-e9c1bkb79qfnii1srbqpitssnu.png)

**Comment by OscarGodson** [comment]
Yep, I was right. Look at this HTML for gods sake:

![https://img.skitch.com/20120519-ges7hy1bhie95dgm97hmxcjq1s.png](https://img.skitch.com/20120519-ges7hy1bhie95dgm97hmxcjq1s.png)

I think our get/setText functions are going to have to do more cleanup probably.

**Comment by OscarGodson** [comment]
Fixed lists:

![example](https://img.skitch.com/20120519-jqs7htha55gsju4xxc6qpe6y9f.png)
![example](https://img.skitch.com/20120519-e4tfatck57ts5mqcdya84c69ti.png)

The table issue is part of a much, much bigger issue now though. You see... Firefox doesn't support innerText like every other browser so I can't get the pure text of the page which includes `<table>` or any other text a user put in. Firefox converts `<table>` to `&lt;table&gt;`. So, after ripping all the HTML out I need to now convert the lt and gt entities back into HTML. This is gonna get dirty I think...

The issue was that

**Comment by OscarGodson** [comment]
Nevermind. That was easy. Pushing a fix.

**Comment by OscarGodson** [comment]
@dadambickford can you please verify this. Works good in FF on my end tho now: 

![table](https://img.skitch.com/20120519-8fe1hwryb3m21h5inmmtnynisx.png)

**Comment by dadambickford** [comment]
yeah it looks fine in FF for me as well, and the `<li>` is rendering correctly so i'll go over #64 again today and double check that all the styles look correct with anchor tags and code tags
