### ISSUE TITLE
Alt-O not working (OSX)

### ISSUE THREAD

**Issue by pawelphilipczyk** [OscarGodson/EpicEditor#144]
Hi, 
Alt-O (Opt-O) combination is not working for ó and Ó which is Polish character under this shortcut. 
I guess in otherl languages this might be the issue as well.

**Comment by OscarGodson** [comment]
If you're doing alt+o then yes, it'll catch that key and prevent the input. This is tough because I'd love to have shortcuts and I know a lot of people use them, but no shortcut is going to work across the board (i think).

If you're adding this to your site and it gets mostly Polish visitors you could disable the shortcuts via the options.

Do you have any suggestions on shortcut combos or other way's to fix this?

**Comment by pawelphilipczyk** [comment]
If I can disable the shortcuts then there is nothing more I'd suggest.

This is fantastic editor and thank you for making it!

**Comment by pawelphilipczyk** [comment]
After a moment of using the shortcuts I do have a suggestion that may be not only fixing this problem but also be a usability improvement.
The Alt-P for preview could switch edit/preview mode not just switch to preview mode. So there would be just one shortcut combo for toggling this.

**Comment by OscarGodson** [comment]
Great idea! It also makes sense since we have a single preview/edit toggle button. I'm going to put this on the 1.0 milestone and try to get it into the `0.1.2` release.

**Comment by OscarGodson** [comment]
@pawelphilipczyk can you pull develop? @jeffhill actually sent a pull request for this and fixed it! I just pulled it in and tested it and it appears to be working good for me :)

**Comment by pawelphilipczyk** [comment]
I've pulled it and tested it. The Alt-P works fine and Alt-O no longer blocks my ó character. I have other problem but this might be not related to EpicEditor at all. I'm using it with Drupal and [EpicEditor](http://drupal.org/sandbox/erikwebb/1674176) module. After hitting Alt-P the textarea loses focus and to switch back to edit mode I have to click it before I can hit Alt-P again. I'll check that with module maintainer over there but maybe you have any thoughts on that? Here's module [issue](http://drupal.org/node/1690726) link on drupal.org.

**Comment by CashWilliams** [comment]
I'm cross posting this from the Drupal issue linked above.

What I'm seeing is that Alt-P enters Preview mode, but pressing P again (without lifting Alt) does not return to edit. However, if I lift all keys, and then press Alt-P, I will return to edit mode.

This may be a limitation of the OS?  (OSX 10.7 for me)

**Comment by pawelphilipczyk** [comment]
I thought I have to click the textarea but you're right - it's lifting the Alt key that needs to be done. I'm on OSX 10.7 as well.

**Comment by OscarGodson** [comment]
@CashWilliams @pawelphilipczyk Yes, this is an annoying patch I had to make for a pretty major bug. The bug (#133 and #127) would prevent you from typing any shortcut characters (`f`, `s`, `p`, and `o`) at all into the editor mainly on Windows, but sometimes Mac and Linux.

The problem is that when you hit alt+p to preview the focus on the editor is lost and the focus goes on the previewer therefore you never "keyup" on the previewer so then the `alt` key thinks it's still pressed. The only fix I could think of was to cancel out all key shortcuts after each successful shortcut completion. This is why you have to let go of alt and press it again.

I'm sure there's a clever hack to get this working the way it should but I couldn't think of any. Suggestions or ideas?

Here's the actual code that's doing this: https://github.com/OscarGodson/EpicEditor/blob/14226619ba8e1e03d5723aa46da2daeb69eec189/epiceditor/js/epiceditor.js#L756-L760

**Comment by OscarGodson** [comment]
I should add that I went with this fix because if you aren't just playing with EE you probably wouldn't need/want to flip from preview to edit immediately. More than likely you'll switch to preview, read your preview, maybe scroll the preview, etc _then_ flip back to edit mode.

If this does become a major problem tho out in the wild we'll try to come up with some other more clever solution.
