### ISSUE TITLE
Incorrect markdown → html transition in Opera

### ISSUE THREAD

**Issue by samdark** [OscarGodson/EpicEditor#155]
At the project website Opera translates markdown text into incorrect HTML.

**Comment by OscarGodson** [comment]
Thanks for the report. We haven't tested much in Opera, but the little testing we did showed it needed a lot of work. In fact, more work than IE which makes me sad. The Opera browser share is tiny, so I'll try to get to this, but IE and mobile will come first unless someone wants to send a pull request :)

**Comment by OscarGodson** [comment]
Unless I get more reports about Opera im closing this. Out of ~60,000 hits to EpicEditor only 864 were from Opera. The amount of time to get it to work would probably outweigh the amount of use it'd get. I'm open to a pull request tho.

**Comment by samdark** [comment]
That's sad to hear. In US Opera isn't that big but, for example, in Russia it has a huge market share.

**Comment by OscarGodson** [comment]
@samdark Of the ~2.7% of users of EpicEditor from Russia the majority use Chrome by far, then Firefox at about a third of Chrome, then Safari, then Opera. Opera appears to be higher than IE, but it's still in the 1% of the 2.7% of Russian users (or, that's what my analytics says).

**Comment by samdark** [comment]
That's because it doesn't work in Opera obviously. It's not correct to judge by numbers at the project website. Only tech people are using it. Regular users aren't interested in tech.

**Comment by samdark** [comment]
Anyway, the decision is yours. It's not really critical, just a suggestion.

**Comment by OscarGodson** [comment]
@samdark Very true, but the developer wouldn't know it didn't work until he got to the site and by the time he did he'd be tracked. Even so I took a look at: http://gs.statcounter.com/#browser-RU-monthly-201012-201212 and Opera is indeed a popular browser in Russia, but it's still low at 14.6% and has been declining consistently for almost 2 years and rapidly as of late (almost 1% every month).

If the target market was just Russia I'd for sure take the time to do it, but since it's just me I'm trying to prioritize my time on the top browsers by overall global use :(

**Comment by samdark** [comment]
Makes sense. If I'll be back to the project I've tried it for, I'll send a pull request.

**Comment by OscarGodson** [comment]
@samdark good news, looks like EpicEditor will be supporting Opera in the near future :) http://my.opera.com/ODIN/blog/300-million-users-and-move-to-webkit

**Comment by samdark** [comment]
He-he. Yeah. Good news for both developers and users: less engines to support and we're getting Chrome with Opera's excellent UI and keyboard navigation.
