### ISSUE TITLE
Full screen doesn't work when editor is placed in a frame (tested in Chrome & IE)

### ISSUE THREAD

**Issue by andrejohansson** [OscarGodson/EpicEditor#193]
If the editor is part of a frame based layout, full screen doesn't seem to work. It maximizes within the current frame and not over the screen. See attached images.

![before.PNG](https://f.cloud.github.com/assets/2828428/3071/b36710ce-429e-11e2-9563-8618218eb179.PNG)
![after.PNG](https://f.cloud.github.com/assets/2828428/3072/b37e208e-429e-11e2-9793-457874750a7d.PNG)

**Comment by OscarGodson** [comment]
Do you have a JSBin of this to demo? What kind of frames, `<iframe>`s or old school `<frame>`s? 

If you mean `<iframe>`s I think that's just a limitation of Chrome. I don't think it lets you fullscreen things in iframes on top of the window from a child iframe. Since you click the fullscreen button _in_ an iframe (EpicEditor's iframe it generates), it will try to open in it's parent window which happens to be your iframe therefore opening fullscreen to that iframe window. You could _probably_ set something up so that when you click on fullscreen in EpicEditor have the parent window holding the iframes trigger a fullscreen on that iframe. Like:

``` js
// This code goes in the document which contains your iframes
// editor is a reference to your EpicEditor instance
editor.on('fullscreenenter', function () {
  // Here ask for permission to open your iframe containing EE to open in fullscreen
});
```

As for IE, they don't have an API for fullscreening things. IE and Firefox's fullscreen are faked by EpicEditor. They simply get the width and height of the document and then expand to that size. Since iframes have their own document it sees the iframe (like Chrome) as the document to fit inside of. You would need to do the same thing I believe for IE as Chrome, but you wouldn't need to do the `webkit.requestFullscreen` or whatever.

The problem is, I don't think it's possible for EpicEditor to know how many levels it needs to go up to find the upper-most parent. I believe you can only tell if you're in a frame with `if (top === self)`, but there's no way to know _which_ frame is the parent frame.

cc: @johnmdonahue

**Comment by OscarGodson** [comment]
Until someone knows of an idea to get to the uppermost frame (i dont think it's possible) I'll keep it closed since there's not much I can do. Suggestions welcome tho!
