### ISSUE TITLE
Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by mjuchli** [OscarGodson/EpicEditor#194]
Sometimes - and I've still no clue why - I got the following error during editor.importFile on load: 
Uncaught SyntaxError: Unexpected token ILLEGAL 

Any ideas?

See about line 40: https://github.com/backender/BackenderEpiceditorBundle/blob/master/Resources/views/Form/epiceditor_widget.html.twig

**Comment by OscarGodson** [comment]
I'd need to see the generated source when the error happens. Could you send that?

**Comment by OscarGodson** [comment]
One thing tho that looks to be problematic is that you're importing the text from some other source and because you have it wrapped in single quotes, if your text your importing has single quotes it'll give you an error because, for example:

`.importFile('', 'i'm')`

 is invalid in JS. That's a limitation of JS and most programming languages I can think of. If that's _not_ it please let me know so we can reopen the issue :)
