### ISSUE TITLE
Styling doesn't work when stylesheets are precompiled into one stylesheet

### ISSUE THREAD

**Issue by mindscratch** [OscarGodson/EpicEditor#200]
EpicEditor relies on several stylesheets for the editor and preview mode. When using Rails in production I precompile all of my assets (javascript, stylesheets, etc). The result is a single CSS file which combines all other CSS used by the application. Since the EpicEditor stylesheets aren't 100% name spaced some of the styles get overridden causing the editor to not look the way it should all the time.

**Comment by OscarGodson** [comment]
It used to be this way: https://github.com/OscarGodson/EpicEditor/blob/0.0.3/epiceditor/themes/preview/github.css

There were a couple problems:
1. It'd made the theme's CSS super ugly and not scannable.
2. It made it so you can't mix and match themes. I.e. If you wanted to use the github theme for editing you couldn't or would have to manually go and change every style. This is a big problem too because eventually the editor will style the text as you type. As an example, see Mou.

Do you have any ideas or suggestions? Is there an automated way possibly?

**Comment by mindscratch** [comment]
It might be possible to have the EpicEditor CSS files left untouched and just have them served on their own as needed, for my use case that would be feasible. I'll think about it a little more, maybe there's some better way.

**Comment by OscarGodson** [comment]
Yeah... so could you just load the EE assets when you need it (also known as lazy loading modules) or is EE loaded on every page? im also very curious what you're building :)

**Comment by mindscratch** [comment]
I'm working on the admin section of a custom blog. 

So far I haven't found a way of loading some assets outside of the Rails asset pipeline when in "production" mode, Rails gives: ActionView::Template::Error (epiceditor.css isn't precompiled)

**Comment by OscarGodson** [comment]
I don't know rails well enough but we have different packages that get depending on what part of the app you're on. Like, a base package, then an admin package. Hmm.

**Comment by mindscratch** [comment]
I'm actually looking at using PageDown-Bootstrap now. It seems to have the main features I was interested in and I think the CSS won't be an issue: http://samwillis.co.uk/pagedown-bootstrap/demo/browser/demo.html
