### ISSUE TITLE
Paste doesn't paste plaintext

### ISSUE THREAD

**Issue by relipse** [OscarGodson/EpicEditor#222]
I was trying to copy and paste some code from http://daringfireball.net/projects/markdown/syntax
and it actually copied the background color and table and everything

It should paste only the plaintext

**Comment by OscarGodson** [comment]
Known: https://github.com/OscarGodson/EpicEditor/issues/100

This has been attempted to be fixed by me and two others with no luck. Feel free to try yourself. You can also see my commits to try to fix it, but none quite do the job :\

As a workaround, you can paste plain text in your browser with cmd+shift+v (at least on mac). Maybe try ctrl+shift+v on Windows.
