### ISSUE TITLE
Request: Add requirejs use case to documentation

### ISSUE THREAD

**Issue by azhang** [OscarGodson/EpicEditor#262]
It took a while for me to figure out how to use EpicEditor with Requirejs and Backbone, because I assumed I assumed I had to shim this to work with Requirejs. I thought EpicEditor was the object being exported, when actually marked was. However after looking at the code, I realized that nothing needed to be done except for the following. I think it would help to put this in the documentation.

In the requirejs config:

```
paths: {
    [...],
    'marked': 'libs/EpicEditor-v0.2.1.1/js/epiceditor'
}
```

In file that needs EpicEditor loaded:

```
define([
  'marked'
], function(marked){
```

**Comment by OscarGodson** [comment]
Both EpicEditor and Marked are exported to window. Marked is exported because the parser is totally separate from EpicEditor (you can use any parser). 

I made a new wiki page, EpicEditor with Module Loaders. Feel free to expand on it to make it work with RequireJS as I've never used it. Thank you! I'm sure this will be useful to a lot of other people. If I get a bunch of questions about it in the future I'll put it in the main docs.

**Comment by OscarGodson** [comment]
Oops, here's a link: https://github.com/OscarGodson/EpicEditor/wiki/EpicEditor-with-Module-Loaders

**Comment by azhang** [comment]
Awesome, thanks!

**Comment by OscarGodson** [comment]
No, thank _you_!
