### ISSUE TITLE
Make it more modulable

### ISSUE THREAD

**Issue by siscia** [OscarGodson/EpicEditor#301]
Hi guys,

I really appreciate your work that is really good, but it is a little useless for my meaning, I find it too strict.

Let me explain:

I have some fairly complex page, and I would like to add EpicEditor to it, however the two frames are really problematic, I cannot rewrite all the css just to match the two frames... Nor I am able to...

Would be very cool if you let me decide what `id` should contain the editor and what `id` should contain the preview, if I don't want the css to intersecate in any way I will use 2 iframes, otherwise I will use some other structure...

**Comment by OscarGodson** [comment]
Question, why do you need to rewrite all of your CSS? If you just want to style the editor, why can't you simply link the editor/preview "theme" CSS to your current CSS file in the options?

## Word of caution

EpicEditor didn't use to be in an iframe. The reason EpicEditor is in an iframe is not just because the CSS will collide, also other JS and the DOM inside will always be reliable and not changed by some random jQuery plugin on the page. The original version that did not have iframes and became a huge headache for these reasons. This would also require UI work to figure out where the toolbar would then go and how it'd act. I'd never say never, but out of the box, we will probably never allow you to put the editor and previewer outside of the wrapping iframes and just into some random element. The amount of bugs that aren't really bugs but because of other JS and stuff on the page would become too unwieldily for me alone.

One example: There was one issue someone couldn't figure out why his code blocks in his MD were getting all jumbled up. After spending hours trying to debug on my end, he wrote to me and said he found it and it was some plugin he installed from WP to colorize his code blocks.

## Workarounds

Moving the physical editor out of an iframe will be tough because 95% of the code revolves around that part, but as for the preview, that's super easy. You can simply do something like:

``` js
var myCustomPreviewDiv = document.querySelector('#preview');
var editor = new EpicEditor({ button: { bar: 'hide' } });
editor.on('update', function () {
  myCustomPreviewDiv.innerHTML = this.exportFile(null, 'html');
});
editor.load();
```

So, whenever the editor is updated, update some div with the generated MD. We also hid the button bar so you can't click the preview button.

**Comment by siscia** [comment]
I haven't found a way to make it works without re-write the css, definitely I am not a FrontEnd guy, so it may be just me not able to, but still... (basically I want the editor to be a textarea of a particular class inside a particular id, can I achieve it somehow ?)

Definitely makes sense the iframe from the javascript point of you, however it bothers me that some random js from some random script can bother so much, one of the bigger reason why I don't like js.

I would love to try to figure out something, but I don't think it is even possible.

Thanks again for your work, it is greatly appreciate.

**Comment by siscia** [comment]
The only thing I can think about is that maybe the project is growing too big...

I will probably try to make something smaller myself, even if js don't even figure out in my CV

**Comment by OscarGodson** [comment]
The problem about JS you're talking about isn't JS, but a DOM issue. All the code shares the same UI. It could be python and the DOM would still have that issue ;) (for comparison Node doesnt run into this)

Is the main issue you need to submit a form with a textarea? You mention the textarea so I'm guessing maybe you have a form with a textarea and that has to be submittable? Have you seen the textarea option? It'll hide the textarea but it'll still be on the page and the editor content will be synced.

If the only thing you want is a textarea and then it to be parsed and spit into a div, you can just take the parser, github.com/chjj/Marked, and then add a keypress event to the textarea and whenever a key is pressed take the value, parse with Marked and spit it into your div. It'll be much smaller and lightweight if that's what you need :)

This project is pretty small. Its one of the smallest editor + parsers. To put it in comparison, CodeMirrors parser alone is larger than this entire project including the 3 themes ;)

**Comment by siscia** [comment]
Hi, 
yeah, javascript client-side I "tried to mean", still, nowadays front-end develop is such a big deal that should be possible to make code that works only on a particular node of the DOM and raise ~~error~~ exception if applied some where else...

It doesn't look so impossible...

Yes, i am going to use marked and just spit out the HTML.

Thanks for the suggestion.

**Comment by OscarGodson** [comment]
They are starting to do that with "shadow DOM". Hasn't taken off yet tho :)

let me know of you have any problems with that. Happy to help with getting marked working to it taking a content from a textarea and putting it somewhere else. Email me (I believe my email is public on my profile)
