### ISSUE TITLE
Tabindex

### ISSUE THREAD

**Issue by arsensokolov** [OscarGodson/EpicEditor#318]
How to correct to set tabindex to editor field.

**Comment by OscarGodson** [comment]
You mean like, how to make it so you can tab into it while in an input before it? Since EpicEditor isn't a textarea you can't technically tab into it. You can do some "hacks" tho such as setting the a keypress event on the input before it for tab. As an example you have:

``` html
<input name="title" id="title-input">
<div id="epiceditor"></div>
```

Then, for JS:

``` js
var editor = new EpicEditor().load();
$('#title-input').on('keyup', function (e) {
  if (e.keyCode == 9) editor.focus();
});
```

I havent tested that, but it _should_ work.

**Comment by OscarGodson** [comment]
Also, adding this as a feature request for the epiceditor div to support a "tabindex" attribute and it would handle setting this up for you.

**Comment by arsensokolov** [comment]
Thank you. Everything works fine.
