### ISSUE TITLE
Don't work with <input> and  <text-area>

### ISSUE THREAD

**Issue by myguidingstar-zz** [OscarGodson/EpicEditor#73]
This seems to work with div only.
And can anybody show me how to include epiceditor to a form so that its content can be sent via POST?

**Comment by OscarGodson** [comment]
I'm not really sure what you mean exactly about working with an `<input>` or `<textarea>`? Could you explain? It'll work in any containing element (you could put it in a `<span>` if you really wanted), but there's no way any editor could work in an input so I'm thinking you might mean something else.

So, `0.0.3` is finished and `0.1.0` is _almost_ complete. I'm mainly writing tests and need to finish IE9 bug fixes, but otherwise done _so_ you should check out the `0.1.0-build-refactor` branch and these method calls are referring to new/replaced methods:

``` javascript

// EpicEditor will automatically look for something with the id="epiceditor" in 0.1.0
// otherwise you should set it like EpicEditor({ container: 'some-id' })
var editor = new EpicEditor();

// Load the editor
editor.load();

// jQuery is used just for example's sake
$('#some-btn').on('click', function(){
  // exportFile() returns raw text in the editor
  var editorContent = editor.exportFile();
  // jQuery POST request
  $.post('/send/here',{content:editorContent});
});
```

**Comment by myguidingstar-zz** [comment]
Well, stuff such as <input id="something" ...> don't work. Anyway, I want an editor that can be embed to HTML forms' textareas (a working form combined by several input fields with not much further work), so I made some changes to pagedown: https://github.com/myguidingstar/pagedown/tree/master/demo/jquery
Even though, I still prefer epiceditor's clean look.

**Comment by OscarGodson** [comment]
I think you might be confused at what EpicEditor is. EpicEditor is purely a UI for an editor. You can't embed an editor into an input. EpicEditor is a series of iframes embedded in each other and stores values of those iframes in localStorage and gives you a set of APIs to get the data to store server side. Pagedown is a markdown converter. EE uses Marked for converting, but EE isn't a MD converter so it can't be embedded into an input. You can put the editor into a form easily by just putting a div in a form, but as I said, it's not a parser.

**Comment by OscarGodson** [comment]
Also FWIW you can't embed an editor like this into a textarea. You can't display HTML in a textarea, it'll just be text. Hopefully that makes sense... Maybe I don't fully understand you either, because I'm not sure I understand how or why youd put an editor in an input. Do you have a love sample of what you're trying to mimic with EE?

**Comment by OscarGodson** [comment]
Ugh I'm on a phone so I can't edit my posts, love example should be LIVE example.

**Comment by myguidingstar-zz** [comment]
Thank you for your details. Before your posts, I just think EE work by making iframes so it doesn't fit my needs.
