### ISSUE TITLE
Allow override of linting is jake build

### ISSUE THREAD

**Issue by OscarGodson** [OscarGodson/EpicEditor#89]
I was trying to debug an issue and added a `debugger` which made it impossible to run `jake build` without modifying the .jslintrc file to allow `debugger` statements. It'd be nice if the `jake build` command allowed a `-f` (force) flag to override linting. Maybe it gives a warning or something in the output when you force like:

``` bash
WARNING: Building without linting should only be used for development purposes. Please rerun with linting before pushing.
```

**Comment by johnmdonahue** [comment]
So between this and #89, maybe a less strict `.jshintrc` would make since here. I'll play with some options:
1. Make JSHint allow debug statements
2. Set up build task to allow bypass of lint for dev using a flag as suggested `-f`
3. Make build not require lint, and instead setup commit hooks to check modified vs build stamps (this would make sense for docs as well)

**Comment by OscarGodson** [comment]
For #1 i'd rather _not_ allow it to have debug statements so that one doesn't slip into a public build. For commit hooks, that'd be fine, but do commit hooks have to be enabled for each dev or when they clone the repo do they just appear?

**Comment by johnmdonahue** [comment]
Yeah. Scratch that - git hooks aren't shared but it would still be a nice thing to have if just for sanity checks to build before pushing. The `nolint` flag is in place on the jakefile refactor here: https://github.com/OscarGodson/EpicEditor/tree/jakefile-cleanup

``` bash
$ jake build[somearg,nolint,someotherarg] # arg position doesn't matter but no spaces are permitted between args
```

**Comment by OscarGodson** [comment]
Just checked it, and it works for me!
